# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  rootfs = {
    pname = "rootfs";
    version = "bionic-20220805";
    src = fetchurl {
      url = "https://cloud-images.ubuntu.com/bionic/20220805/bionic-server-cloudimg-amd64-wsl.rootfs.tar.gz";
      sha256 = "sha256-QOBUkDoUrvkozGdCbFTMbpt1wTh/NoAo+yMonWVoBQU=";
    };
  };
}
