# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  rootfs = {
    pname = "rootfs";
    version = "22.04-20220902";
    src = fetchurl {
      url = "https://cloud-images.ubuntu.com/releases/22.04/release-20220902/ubuntu-22.04-server-cloudimg-amd64-wsl.rootfs.tar.gz";
      sha256 = "sha256-Kjhyf3/1c2NKI8Ry43cryMjY2wMkvARy5f5iFbJr/7Q=";
    };
  };
}
