# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rootfs = {
    pname = "rootfs";
    version = "20221001";
    src = fetchurl {
      url = "https://repo-default.voidlinux.org/live/20221001/void-x86_64-ROOTFS-20221001.tar.xz";
      sha256 = "sha256-/8IQMCzPFt+Z0hYJYR4v8vRqb77ezeciCkzIgCZM+Uk=";
    };
  };
}
