# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  rootfs = {
    pname = "rootfs";
    version = "20210930";
    src = fetchurl {
      url = "https://repo-default.voidlinux.org/live/20210930/void-x86_64-ROOTFS-20210930.tar.xz";
      sha256 = "sha256-hoGwYOOeFzaC4XIaYIgoDCtureYo9eXj6OS3QWPRh/Y=";
    };
  };
}
