# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  rootfs = {
    pname = "rootfs";
    version = "3.16.1";
    src = fetchurl {
      url = "https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64/alpine-minirootfs-3.16.1-x86_64.tar.gz";
      sha256 = "sha256-5DQcRdD9IzZCs08aNGgGXiryAmsZhZOLKzgnd8I9TTE=";
    };
  };
}
